services:

  web:
    image: nginx:1.27.2-alpine
    network_mode: "host"
    volumes:
      - ./docker/nginx/conf.d/dev_proxy.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:7.4.1-alpine
    network_mode: "host"